import type { User, Ticket, Note } from './definitions';

export const users: User[] = [
  { id: 'USR-1', name: 'Sarah Lee', email: 'sarah.lee@example.com', avatarUrl: 'https://picsum.photos/seed/1/100/100', role: 'Agent' },
  { id: 'USR-2', name: 'Mike Chen', email: 'mike.chen@example.com', avatarUrl: 'https://picsum.photos/seed/2/100/100', role: 'Agent' },
  { id: 'USR-3', name: 'Emily Rodriguez', email: 'emily.r@example.com', avatarUrl: 'https://picsum.photos/seed/3/100/100', role: 'Manager' },
  { id: 'USR-4', name: 'David Kim', email: 'david.kim@example.com', avatarUrl: 'https://picsum.photos/seed/4/100/100', role: 'User' },
];

export const tickets: Ticket[] = [
  {
    id: 'TKT-001',
    subject: 'Cannot connect to company Wi-Fi',
    description: 'My laptop is unable to connect to the "Corporate" Wi-Fi network. I have tried restarting my machine and forgetting the network, but the issue persists. My colleagues in the same area are not facing this problem.',
    status: 'Open',
    priority: 'High',
    category: 'Network',
    createdAt: new Date('2023-10-26T10:00:00Z'),
    updatedAt: new Date('2023-10-26T10:00:00Z'),
    submitterId: 'USR-4',
    assigneeId: 'USR-1',
  },
  {
    id: 'TKT-002',
    subject: 'Request for Adobe Photoshop License',
    description: 'I need a license for Adobe Photoshop for a new design project. My manager has approved this request. Please let me know the process for installation.',
    status: 'In Progress',
    priority: 'Medium',
    category: 'Software',
    createdAt: new Date('2023-10-26T11:30:00Z'),
    updatedAt: new Date('2023-10-27T14:00:00Z'),
    submitterId: 'USR-4',
    assigneeId: 'USR-2',
  },
  {
    id: 'TKT-003',
    subject: 'Printer is not working',
    description: 'The main office printer on the 3rd floor (Model HP LaserJet Pro M404dn) is displaying a "Paper Jam" error, but there is no visible paper jam. I have tried turning it off and on again.',
    status: 'Resolved',
    priority: 'Medium',
    category: 'Hardware',
    createdAt: new Date('2023-10-25T09:00:00Z'),
    updatedAt: new Date('2023-10-25T15:45:00Z'),
    submitterId: 'USR-4',
    assigneeId: 'USR-1',
  },
  {
    id: 'TKT-004',
    subject: 'Password Reset for CRM',
    description: 'I have forgotten my password for the company CRM and am now locked out after too many failed attempts. I need an urgent password reset to access client data.',
    status: 'Closed',
    priority: 'Critical',
    category: 'Account',
    createdAt: new Date('2023-10-24T16:20:00Z'),
    updatedAt: new Date('2023-10-24T16:50:00Z'),
    submitterId: 'USR-4',
    assigneeId: 'USR-2',
  },
  {
    id: 'TKT-005',
    subject: 'Suspicious Email Received',
    description: 'I received an email pretending to be from our CEO asking for gift card purchases. I did not click any links, but I wanted to report it to the security team.',
    status: 'Open',
    priority: 'High',
    category: 'Security',
    createdAt: new Date('2023-10-27T13:00:00Z'),
    updatedAt: new Date('2023-10-27T13:05:00Z'),
    submitterId: 'USR-4',
    assigneeId: 'USR-3',
  },
  {
    id: 'TKT-006',
    subject: 'Monitor flickering issue',
    description: 'My secondary monitor has started flickering intermittently. I have checked the cable connections, and they seem secure.',
    status: 'In Progress',
    priority: 'Low',
    category: 'Hardware',
    createdAt: new Date('2023-10-27T15:00:00Z'),
    updatedAt: new Date('2023-10-27T15:00:00Z'),
    submitterId: 'USR-4',
    assigneeId: null,
  },
];

export const notes: Note[] = [
    {
        id: 'NOTE-001',
        ticketId: 'TKT-001',
        authorId: 'USR-1',
        content: "Checked user's device settings. It seems to be a profile corruption issue. Will attempt to re-provision the Wi-Fi profile.",
        createdAt: new Date('2023-10-26T10:30:00Z'),
    },
    {
        id: 'NOTE-002',
        ticketId: 'TKT-002',
        authorId: 'USR-2',
        content: 'Photoshop license has been procured. Sending installation instructions to the user.',
        createdAt: new Date('2023-10-27T14:00:00Z'),
    },
    {
        id: 'NOTE-003',
        ticketId: 'TKT-003',
        authorId: 'USR-1',
        content: 'Found a small piece of paper stuck deep inside the printer roller. Removed it and tested the printer. It is now functioning correctly.',
        createdAt: new Date('2023-10-25T15:40:00Z'),
    },
    {
        id: 'NOTE-004',
        ticketId: 'TKT-003',
        authorId: 'USR-1',
        content: 'Resolved. The printer is back online.',
        createdAt: new Date('2023-10-25T15:45:00Z'),
    },
    {
        id: 'NOTE-005',
        ticketId: 'TKT-004',
        authorId: 'USR-2',
        content: "User's account has been unlocked and a temporary password has been sent via secure channel.",
        createdAt: new Date('2023-10-24T16:45:00Z'),
    },
];
